spring:
  jpa:
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/apiservice?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/apiservice?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8

server:
  port: 9091

